### ISSUE TITLE
bitcoin-s depdendency does not resolve

### ISSUE THREAD

**Issue by Christewart** [benthecarman/PSBT-Toolkit#3]
When running `test:compile` 

>[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.bitcoin-s:bitcoin-s-core_2.13:0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/suredbits/.ivy2/local/org.bitcoin-s/bitcoin-s-core_2.13/0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/bitcoin-s/bitcoin-s-core_2.13/0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT/bitcoin-s-core_2.13-0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/bitcoin-s/bitcoin-s-core_2.13/0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT/bitcoin-s-core_2.13-0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT.pom
[error] Error downloading org.bitcoin-s:bitcoin-s-testkit_2.13:0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/suredbits/.ivy2/local/org.bitcoin-s/bitcoin-s-testkit_2.13/0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/bitcoin-s/bitcoin-s-testkit_2.13/0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT/bitcoin-s-testkit_2.13-0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/bitcoin-s/bitcoin-s-testkit_2.13/0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT/bitcoin-s-testkit_2.13-0.3.0+416-e1db81d0-SCHNORR-DLC-SNAPSHOT.pom
[error] Total time: 2 s, completed Oct 30, 2020, 7:06:12 AM

**Comment by benthecarman** [comment]
Should be fixed by 382db5a
